# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Naodai's Blog
email: zhao_brain#163.com
description: > # this means to ignore newlines until "baseurl:"
    记录工作和生活的点滴。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://naodai.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: naodai 

# Build settings
markdown: kramdown

#theme
remote_theme: Hacker

gems: [jekyll-paginate]

#paginate
paginate: 10
paginate_path: "page:num"
